# http port set
server:
  port: 8195 
  
spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  
  # Oracle Connect 
 
  datasource:
    url : jdbc:oracle:thin:@localhost:1521:xe
    username: S20220101
    password : tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

  # ORM JPA
  jpa:
    hibernate:
       ddl-auto: none
   
  # gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: jbh9609@gmail.com
    password: 1!byeonghunGOOGLE
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true 
 
       
  #view resolver(Templete ->JSP Use)
  mvc:
     view:
       prefix: /WEB-INF/views/
       suffix: .jsp
  
  
#Mybatis
mybatis: 
   # dto Location 
   type-aliases-package: com.oracle.BlockBuster.model
   # xml location
   config-location: classpath:configuration.xml
   mapper-locations: classpath:mappers/*.xml